<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 482,
                'name' => '根对象',
                'path' => '/',
                'method' => 'GET',
                'description' => '根对象',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-02 14:14:55',
                'parent_id' => 0,
            ),
            1 => 
            array (
                'id' => 483,
                'name' => 'permission',
                'path' => '/permission',
                'method' => 'GET',
                'description' => '权限测试页',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 482,
            ),
            2 => 
            array (
                'id' => 484,
                'name' => 'PagePermission',
                'path' => '/permission/page',
                'method' => 'GET',
                'description' => '页面权限',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 483,
            ),
            3 => 
            array (
                'id' => 485,
                'name' => 'DirectivePermission',
                'path' => '/permission/directive',
                'method' => 'GET',
                'description' => '指令权限',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 483,
            ),
            4 => 
            array (
                'id' => 486,
                'name' => 'Icons',
                'path' => '/icon',
                'method' => 'GET',
                'description' => '图标',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 482,
            ),
            5 => 
            array (
                'id' => 487,
                'name' => 'Icons',
                'path' => '/icon/index',
                'method' => 'GET',
                'description' => '图标',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 486,
            ),
            6 => 
            array (
                'id' => 488,
                'name' => 'ComponentDemo',
                'path' => '/components',
                'method' => 'GET',
                'description' => '组件',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 482,
            ),
            7 => 
            array (
                'id' => 489,
                'name' => 'TinymceDemo',
                'path' => '/components/tinymce',
                'method' => 'GET',
                'description' => '富文本编辑器',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            8 => 
            array (
                'id' => 490,
                'name' => 'MarkdownDemo',
                'path' => '/components/markdown',
                'method' => 'GET',
                'description' => 'Markdown',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            9 => 
            array (
                'id' => 491,
                'name' => 'JsonEditorDemo',
                'path' => '/components/json-editor',
                'method' => 'GET',
                'description' => 'JSON编辑器',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            10 => 
            array (
                'id' => 492,
                'name' => 'SplitpaneDemo',
                'path' => '/components/splitpane',
                'method' => 'GET',
                'description' => 'Splitpane',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            11 => 
            array (
                'id' => 493,
                'name' => 'AvatarUploadDemo',
                'path' => '/components/avatar-upload',
                'method' => 'GET',
                'description' => '头像上传',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            12 => 
            array (
                'id' => 494,
                'name' => 'DropzoneDemo',
                'path' => '/components/dropzone',
                'method' => 'GET',
                'description' => 'Dropzone',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            13 => 
            array (
                'id' => 495,
                'name' => 'StickyDemo',
                'path' => '/components/sticky',
                'method' => 'GET',
                'description' => 'Sticky',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            14 => 
            array (
                'id' => 496,
                'name' => 'CountToDemo',
                'path' => '/components/count-to',
                'method' => 'GET',
                'description' => 'CountTo',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            15 => 
            array (
                'id' => 497,
                'name' => 'ComponentMixinDemo',
                'path' => '/components/mixin',
                'method' => 'GET',
                'description' => '小组件',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            16 => 
            array (
                'id' => 498,
                'name' => 'BackToTopDemo',
                'path' => '/components/back-to-top',
                'method' => 'GET',
                'description' => '返回顶部',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            17 => 
            array (
                'id' => 499,
                'name' => 'DragDialogDemo',
                'path' => '/components/drag-dialog',
                'method' => 'GET',
                'description' => '拖拽 Dialog',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            18 => 
            array (
                'id' => 500,
                'name' => 'DndListDemo',
                'path' => '/components/dnd-list',
                'method' => 'GET',
                'description' => '列表拖拽',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            19 => 
            array (
                'id' => 501,
                'name' => 'DragKanbanDemo',
                'path' => '/components/drag-kanban',
                'method' => 'GET',
                'description' => '可拖拽看板',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 488,
            ),
            20 => 
            array (
                'id' => 502,
                'name' => 'Charts',
                'path' => '/charts',
                'method' => 'GET',
                'description' => '图表',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 482,
            ),
            21 => 
            array (
                'id' => 503,
                'name' => 'KeyboardChart',
                'path' => '/charts/keyboard',
                'method' => 'GET',
                'description' => '键盘图表',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 502,
            ),
            22 => 
            array (
                'id' => 504,
                'name' => 'LineChart',
                'path' => '/charts/line',
                'method' => 'GET',
                'description' => '折线图',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:15',
                'updated_at' => '2018-09-01 14:21:15',
                'parent_id' => 502,
            ),
            23 => 
            array (
                'id' => 505,
                'name' => 'MixChart',
                'path' => '/charts/mixchart',
                'method' => 'GET',
                'description' => '混合图表',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 502,
            ),
            24 => 
            array (
                'id' => 506,
                'name' => 'Nested',
                'path' => '/nested',
                'method' => 'GET',
                'description' => '路由嵌套',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            25 => 
            array (
                'id' => 507,
                'name' => 'Menu1',
                'path' => '/nested/menu1',
                'method' => 'GET',
                'description' => '菜单1',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 506,
            ),
            26 => 
            array (
                'id' => 508,
                'name' => 'Menu1-1',
                'path' => '/menu1/menu1-1',
                'method' => 'GET',
                'description' => '菜单1-1',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 507,
            ),
            27 => 
            array (
                'id' => 509,
                'name' => 'Menu1-2',
                'path' => '/menu1/menu1-2',
                'method' => 'GET',
                'description' => '菜单1-2',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 507,
            ),
            28 => 
            array (
                'id' => 510,
                'name' => 'Menu1-2-1',
                'path' => '/menu1-2/menu1-2-1',
                'method' => 'GET',
                'description' => '菜单1-2-1',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 509,
            ),
            29 => 
            array (
                'id' => 511,
                'name' => 'Menu1-2-2',
                'path' => '/menu1-2/menu1-2-2',
                'method' => 'GET',
                'description' => '菜单1-2-2',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 509,
            ),
            30 => 
            array (
                'id' => 512,
                'name' => 'Menu1-3',
                'path' => '/menu1/menu1-3',
                'method' => 'GET',
                'description' => '菜单1-3',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 507,
            ),
            31 => 
            array (
                'id' => 513,
                'name' => 'Menu2',
                'path' => '/nested/menu2',
                'method' => 'GET',
                'description' => '菜单2',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 506,
            ),
            32 => 
            array (
                'id' => 514,
                'name' => 'Table',
                'path' => '/table',
                'method' => 'GET',
                'description' => 'Table',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            33 => 
            array (
                'id' => 515,
                'name' => 'DynamicTable',
                'path' => '/table/dynamic-table',
                'method' => 'GET',
                'description' => '动态Table',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 514,
            ),
            34 => 
            array (
                'id' => 516,
                'name' => 'DragTable',
                'path' => '/table/drag-table',
                'method' => 'GET',
                'description' => '拖拽Table',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 514,
            ),
            35 => 
            array (
                'id' => 517,
                'name' => 'InlineEditTable',
                'path' => '/table/inline-edit-table',
                'method' => 'GET',
                'description' => 'Table内编辑',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 514,
            ),
            36 => 
            array (
                'id' => 518,
                'name' => 'TreeTableDemo',
                'path' => '/table/tree-table',
                'method' => 'GET',
                'description' => '树形表格',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 514,
            ),
            37 => 
            array (
                'id' => 519,
                'name' => 'CustomTreeTableDemo',
                'path' => '/table/custom-tree-table',
                'method' => 'GET',
                'description' => '自定义树表',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 514,
            ),
            38 => 
            array (
                'id' => 520,
                'name' => 'ComplexTable',
                'path' => '/table/complex-table',
                'method' => 'GET',
                'description' => '综合Table',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 514,
            ),
            39 => 
            array (
                'id' => 521,
                'name' => 'Example',
                'path' => '/example',
                'method' => 'GET',
                'description' => '综合实例',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            40 => 
            array (
                'id' => 522,
                'name' => 'CreateArticle',
                'path' => '/example/create',
                'method' => 'GET',
                'description' => '创建文章',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 521,
            ),
            41 => 
            array (
                'id' => 523,
                'name' => 'EditArticle',
            'path' => '/example/edit/:id(\\d+)',
                'method' => 'GET',
                'description' => '编辑文章',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 521,
            ),
            42 => 
            array (
                'id' => 524,
                'name' => 'ArticleList',
                'path' => '/example/list',
                'method' => 'GET',
                'description' => '文章列表',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 521,
            ),
            43 => 
            array (
                'id' => 525,
                'name' => 'Tab',
                'path' => '/tab',
                'method' => 'GET',
                'description' => 'Tab',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            44 => 
            array (
                'id' => 526,
                'name' => 'Tab',
                'path' => '/tab/index',
                'method' => 'GET',
                'description' => 'Tab',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 525,
            ),
            45 => 
            array (
                'id' => 527,
                'name' => 'ErrorPages',
                'path' => '/error',
                'method' => 'GET',
                'description' => '错误页面',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            46 => 
            array (
                'id' => 528,
                'name' => 'Page401',
                'path' => '/error/401',
                'method' => 'GET',
                'description' => '401',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 527,
            ),
            47 => 
            array (
                'id' => 529,
                'name' => 'Page404',
                'path' => '/error/404',
                'method' => 'GET',
                'description' => '404',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 527,
            ),
            48 => 
            array (
                'id' => 530,
                'name' => 'ErrorLog',
                'path' => '/error-log',
                'method' => 'GET',
                'description' => '错误日志',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            49 => 
            array (
                'id' => 531,
                'name' => 'ErrorLog',
                'path' => '/error-log/log',
                'method' => 'GET',
                'description' => '错误日志',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 530,
            ),
            50 => 
            array (
                'id' => 532,
                'name' => 'Excel',
                'path' => '/excel',
                'method' => 'GET',
                'description' => 'Excel',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            51 => 
            array (
                'id' => 533,
                'name' => 'ExportExcel',
                'path' => '/excel/export-excel',
                'method' => 'GET',
                'description' => 'Export Excel',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 532,
            ),
            52 => 
            array (
                'id' => 534,
                'name' => 'EelectExcel',
                'path' => '/excel/export-selected-excel',
                'method' => 'GET',
                'description' => 'Export Selected',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 532,
            ),
            53 => 
            array (
                'id' => 535,
                'name' => 'UploadExcel',
                'path' => '/excel/upload-excel',
                'method' => 'GET',
                'description' => 'Upload Excel',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 532,
            ),
            54 => 
            array (
                'id' => 536,
                'name' => 'ExportZip',
                'path' => '/zip',
                'method' => 'GET',
                'description' => 'Zip',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            55 => 
            array (
                'id' => 537,
                'name' => 'ExportZip',
                'path' => '/zip/download',
                'method' => 'GET',
                'description' => 'Export Zip',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 536,
            ),
            56 => 
            array (
                'id' => 538,
                'name' => 'Theme',
                'path' => '/theme',
                'method' => 'GET',
                'description' => '换肤',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            57 => 
            array (
                'id' => 539,
                'name' => 'Theme',
                'path' => '/theme/index',
                'method' => 'GET',
                'description' => '换肤',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 538,
            ),
            58 => 
            array (
                'id' => 540,
                'name' => 'ClipboardDemo',
                'path' => '/clipboard',
                'method' => 'GET',
                'description' => 'Clipboard',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            59 => 
            array (
                'id' => 541,
                'name' => 'ClipboardDemo',
                'path' => '/clipboard/index',
                'method' => 'GET',
                'description' => 'Clipboard',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 540,
            ),
            60 => 
            array (
                'id' => 542,
                'name' => 'I18n',
                'path' => '/i18n',
                'method' => 'GET',
                'description' => '国际化',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            61 => 
            array (
                'id' => 543,
                'name' => 'I18n',
                'path' => '/i18n/index',
                'method' => 'GET',
                'description' => '国际化',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 542,
            ),
            62 => 
            array (
                'id' => 544,
                'name' => 'Permission',
                'path' => '/permission2',
                'method' => 'GET',
                'description' => '综合实例',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 482,
            ),
            63 => 
            array (
                'id' => 545,
                'name' => 'PermissionList',
                'path' => '/permission2/list',
                'method' => 'GET',
                'description' => '权限列表',
                'per_type' => 2,
                'created_at' => '2018-09-01 14:21:16',
                'updated_at' => '2018-09-01 14:21:16',
                'parent_id' => 544,
            ),
        ));
        
        
    }
}